#!/usr/bin/env python

# Database scripts

from sqlmodel import SQLModel, Field, Session, create_engine, select # DB
from datetime import datetime, timezone, timedelta
from pathlib import Path
from uuid import uuid4 # Needed to prevent naming conficts in db_users.uuid

# TODO: Initialize SQLModel


# --------------------
# Logging
def log(message: str, level: int | None = None, perm: bool = False):
    log_file = "database_log.txt"
    eval_level = lambda level, perm: "[LOG]   | " if level == 1 else ("[WARN]  | " if level == 2 else ("[ERROR] | " if level == 3 else ("        | " if (level == 0) or (perm) else (""))))
    loggedmessage = eval_level(level, perm) + message
    if perm:
        with open(log_file, "a") as file: # Auto closes it when done
            file.write(loggedmessage + "\n")
            print(f"Logged to database_log.txt: \"{loggedmessage}\"")
    else:
        print(loggedmessage)
            

# --------------------
# Databases (sqlmodel classes)
class db_users(SQLModel, table=True): # User overview
    __tablename__ = "db_users"
    uuid: str = Field(primary_key=True, default_factory=lambda: str(uuid4())) # Dynamically generates the default uuid if one is not provided; lambda since brackets are not allowed
    usernum: int | None = Field(index=True, unique=True, default=None) # Incremental; will be populated by script later on
    username: str = Field(index=True, unique=True)
    email: str = Field(index=True, unique=True)
    password: str # Hashed!
    display_name: str | None = Field(default=None) # May beused later on, None means display name is the same as username
    creation_datetime: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    flags: str = Field(default="") # Status tags, such as ADMIN

class db_jwts(SQLModel, table=True):
    __tablename__ = "db_jwts"
    id: int | None = Field(default=None, primary_key=True) # Incremental; will be populated by script later on
    uuid: str = Field(foreign_key="db_users.uuid", index=True)
    jti: str = Field(index=True, unique=True)

class db_userdata(SQLModel, table=True):
    __tablename__ = "db_userdata"
    id: int | None = Field(default=None, primary_key=True) # Incremental; will be populated by script later on
    uuid: str = Field(foreign_key="db_users.uuid", index=True)
    encrypted_tf: bool
    data_type: str
    data: str



# --------------------
# Functions
# ----------
# Major Account Actions
def adduser(data: dict):
    # 1. Create the object
    to_str = lambda val: str(val) if val is not None else None # Fixes "str(data.get("field", None))" errors
    new_user = db_users(
        uuid = to_str(data.get("uuid")), # .get prevents TyDefaults to None if a uuid is somehow not provided
        usernum = None, # Will be modified later
        username = str(data["username"]),
        email = str(data["email"]),
        password = str(data["password"]), # Hashed!
        display_name = str(data.get("display_name", data["username"])),
        creation_datetime = to_str(data.get("creation_datetime")), # None, as the db will be able to make the datetime when it gets added to DB
        flags = to_str(data.get("flags"))
    )
    with Session(db_users) as session: # Auto opens and closes when the block is finished
        # 2. Stage to memory
        session.add(new_user)
        # 3. Save to disk
        session.commit()
        # 4. Fetch autogenerated fields
        session.refresh(new_user)

        # TODO: UPD UUID





    """
    The following fields are NEEDED:
    - User Number (e.g. #12345678, incremental, not needed now but may be useful in the future)
    - UUID (uuid v4)
    - Username
    - Email
    - Password 
    - Data (blank)
    - Active JWTs (blank, but as soon as the user is created the system should create a web token for the user client)
    - Created At (timestamp)
    -----
    The following fields are under consideration:
    - Account Status Fields (e.g. isadmin, isnotdisabled, etc)

    
    Also, many fields need to be encrypted/hashed (pswd).
    """

def deleteuser():
    with Session(db_users) as session: 
        pass


# ----------
# Change User Data
def changeuseraccountinfo(uuid, field, updvalue, admin_perms=False):
    ALLOWED_FIELDS = {"username", "display_name", "email"} # Safeguarding
    if ((field in ALLOWED_FIELDS) or (admin_perms)):
        with Session(db_users) as session:
            statement = select(db_users).where(db_users.uuid == query_uuid)
            result = session.exec(statement).first()
            if result:
                setattr(uuid, field, updvalue)
                return 0
            else: # User does NOT exist in db
                return 1
    else: # Not a default allowed field, and 
        return 2

def changeusersaveddata():
    with Session(db_userdata) as session:
        pass


# ----------
# Query User
def getuserbyuuid(query_uuid):
    with Session(db_users) as session:
        # 1. Build the statement
        statement = select(db_users).where(db_users.uuid == query_uuid) # Select() selects the table
        # 2. Run the statement and grab the result
        result = session.exec(statement).first() # Return ONE matching object or NONE
        # 3. Use the result
        if result:
            return result
        else:
            return None

def getuserbyusername(query_username):
    with Session(db_users) as session:
        statement = select(db_users).where(db_users.username == query_username)
        result = session.exec(statement.first())
        if result:
            return result
        else:
            return None


# ----------
# Security Stuff
def addjwtid():
    with Session(db_jwts) as session:
        pass

def revokejwtid():
    with Session(db_jwts) as session:
        pass

def checkjti():
    with Session(db_jwts) as session:
        pass

def changeuserpassword(): # Although changeuseraccountinfo() could handle this, it is better to keep sensitive info seperate
    with Session(db_users) as session:
        pass


# ----------
# Startup stuff


# TODO: REPLACE WITH SQL DEFAULT

# 1. Find the absolute path to this script
script_dir = Path(__file__).resolve().parent
# 2. Go up one directory and points to the database file
database_file = script_dir.parent / "database.db"

# SQLite connection string
sqlite_url = f"sqlite:///{database_file}"

# Create the SQLModel engine
engine = create_engine(sqlite_url, echo=False)


def init_db():
	# Creates the DB file and all missing tables
	SQLModel.metadata.create_all(engine)

# Removed Database Creation Script for the default SQLModel db creation script
"""
# Database creation script (should only EVER run once!)
def createdatabase():
    try:
        with open(database_file, "x") as f: # Creates the file and instantly closes it. "X" allows for error logging.
            pass
        print("File created successfully!")
        return 1 # Database CREATED
    except FileExistsError: # Should NOT happen
        print("\033[1;33m[WARNING]\033[0m createdatabase() tried to create database.db, but faced FileExistsError. There may be something wrong with startup(), or database.db was added into root between the time of the check and attempted file creation.") # \033[1;33m sets it to bolded yellow, and \033[0m resets the colors
    except PermissionError:
        print("\033[1;31m[FATAL]\033[0m Does not have permission to create the file.") # \033[1;31m sets it to bolded red, and \033[0m resets the colors
        raise # Errors out

# Startup file check
def startup(ranfromapp):
    if database_file.is_file(): # Checks if the file exists
        return 0 # Database EXISTS
    else:
        if ranfromapp == True: # Since app.py calls on it, we can safely run createdatabase and return its results
            return createdatabase()
        else: # Createdatabase() called this script, and the file creation failed - quits the program to prevent recusive loops
            print("\033[1;31m[FATAL]\033[0m createdatabase() tried to create the database and suceeded, but the file was moved or deleted between the time of creation and checking.") # \033[1;31m sets it to bolded red, and \033[0m resets the colors
            raise FileNotFoundError
            return 2 # Unused status code (failure)         
"""