#!/usr/bin/env python

# Database scripts

from sqlmodel import SQLModel, Field, Session, create_engine, select # DB
from datetime import datetime, timezone, timedelta
from pathlib import Path
from uuid import uuid4 # Needed to prevent naming conficts in db_users.uuid


import security as sec


# --------------------
# Logging
def log(message: str, level: int | None = None, perm: bool = False):
    log_file = script_dir.parent / "logs" / "database_log.txt"
    LEVEL_PREFIXES = {
        0: "        | ",
        1: "[LOG]   | ",
        2: "[WARN]  | ",
        3: "[ERROR] | ",
    }
    eval_level = LEVEL_PREFIXES.get(level, "        | " if perm else "")
    # eval_level = lambda level, perm: "[LOG]   | " if level == 1 else ("[WARN]  | " if level == 2 else ("[ERROR] | " if level == 3 else ("        | " if (level == 0) or (perm) else (""))))
    loggedmessage = eval_level + message
    if perm:
        log_file.parent.mkdir(parents=True, exist_ok=True)  # Ensures the "logs" folder exists
        with open(log_file, "a") as file: # Auto closes it when done
            file.write(loggedmessage + "\n")
            print(f"Logged to database_log.txt: \"{loggedmessage}\"")
    else:
        print(loggedmessage)
            

# --------------------
# Databases (sqlmodel classes)
class db_users(SQLModel, table=True): # User overview
    __tablename__ = "db_users"
    uuid: str = Field(primary_key=True, default_factory=lambda: str(uuid4())) # Dynamically generates the default uuid if one is not provided; lambda since brackets are not allowed
    usernum: int | None = Field(index=True, unique=True, default=None) # Incremental; will be populated by script later on
    username: str = Field(index=True, unique=True)
    email: str = Field(index=True, unique=True)
    password: str # Hashed!
    display_name: str | None = Field(default=None) # May beused later on, None means display name is the same as username
    creation_datetime: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    flags: str = Field(default="") # Status tags, such as ADMIN

class db_jwts(SQLModel, table=True):
    __tablename__ = "db_jwts"
    id: int | None = Field(default=None, primary_key=True) # Incremental; will be populated by SQL automatically
    uuid: str = Field(foreign_key="db_users.uuid", index=True)
    jti: str = Field(index=True, unique=True)
    # Will NOT store JWT

class db_userdata(SQLModel, table=True):
    __tablename__ = "db_userdata"
    id: int | None = Field(default=None, primary_key=True) # Incremental; will be populated by SQL automatically
    uuid: str = Field(foreign_key="db_users.uuid", index=True)
    encrypted_tf: bool
    data_type: str
    data: str



# --------------------
# Functions
# ----------
# Major Account Actions
# TODO: Fix so that instead of returning none, it just doesnt return that line.
def adduser(data: dict):

    with Session(engine) as session: # Auto opens and closes when the block is finished
        # Finds the current largest usernum number, defaulting to 0 if no fields exist
        max_num = (
            session.exec(
                select(db_users.usernum).order_by(db_users.usernum.desc())
            ).first()
        ) or 0

        # 1. Create the object
        to_str = lambda val: str(val) if val is not None else None # Fixes "str(data.get("field", None))" errors
        new_user = db_users(
            uuid = to_str(data.get("uuid")), # .get prevents TypeErrors to None if a uuid is somehow not provided
            usernum = int(max_num + 1), # Since it's not the primary key, we have to manually populate it
            username = str(data["username"]),
            email = str(data["email"]),
            password = str(data["password"]), # Hashed!
            display_name = str(data.get("display_name", data["username"])),
            creation_datetime = data.get("creation_datetime", None), # None, as the db will be able to make the datetime when it gets added to DB
            flags = to_str(data.get("flags"))
        )
        
        # 2. Stage to memory
        session.add(new_user)
        # 3. Save to disk
        session.commit()
        # 4. Fetch autogenerated fields
        session.refresh(new_user)

def deleteuser():
    with Session(engine) as session: 
        pass


# ----------
# Change User Data
# TODO: Optimize and make safer. Also, change input() to something like curses() so that uvicorn doesnt accidently freeze.
# IMPORTANT: for now, do NOT use terminal_override
def changeuseraccountinfo(subject_uuid, field, updvalue,initiating_jwt: str, admin_perms=False, terminal_override=False):
    ALLOWED_USER_FIELDS = {"username", "display_name", "email"} # Safeguarding
    ALLOWED_ADMIN_FIELDS = ALLOWED_USER_FIELDS | {"uuid", "usernum", "password", "creation_datetime"}
    ALLOWED_TERMINAL_FIELDS = ALLOWED_ADMIN_FIELDS | {"flags"}
    if ((field in ALLOWED_USER_FIELDS) or (admin_perms) or terminal_override):
        if admin_perms and not terminal_override: # AdminMode
            jwtresult = checkjwt(initiating_jwt)
            if jwtresult["status"] != "valid": # AdminMode, Invalid JWT
                log(f"ABORTED - An admin tried changing Field \"{field}\" for UUID \"{subject_uuid}\", but had an invalid JWT.", level=2, perm=True)
                return 3
            else: # AdminMode, Valid JWT
                uuidresult = getuserbyuuid(jwtresult["sub"])
                if not (",admin," in uuidresult["flags"]): # AdminMode, Valid JWT, Invalid Adminship
                    log(f"ABORTED - An non-admin tried changing Field \"{field}\" for UUID \"{subject_uuid}\".", level=2, perm=True)
                    return 3
                else: # AdminMode, Valid JWT, Valid Adminship
                    pass # All OK!
        elif not terminal_override: # RegMode
            jwtresult = checkjwt(initiating_jwt, uuid=None, jti=None) # TODO: expects 3 arguements
            if jwtresult["status"] != "valid": # RegMode, Invalid JWT
                log(f"ABORTED - Someone tried changing Field \"{field}\" for UUID \"{subject_uuid}\", but had an invalid JWT.", level=2, perm=True)
                return 4
            else: # RegMode, Valid JWT
                if not (subject_uuid == jwtresult["sub"]): # RegMode, Valid JWT, Invalid User
                    log(f"ABORTED - A different user (\"{jwtresult['sub']}\") tried changing Field \"{field}\" for UUID \"{subject_uuid}\".", level=2, perm=True)
                    return 4
                else: # RegMode, Valid JWT, Valid User
                    pass # All OK!

        if not (field in ALLOWED_ADMIN_FIELDS): # Final check - is it allowed?
            if not terminal_override:
                log(f"ABORTED - UUID (\"{jwtresult["sub"]}\") tried changing Field \"{field}\" for UUID \"{subject_uuid}\", which was NOT permitted by ALLOWED_ADMIN_FIELDS and ", level=2, perm=True)
                return 5
            else:
                userinput = input(f"Are you sure you want to change Field \"{field}\" to \"{updvalue}\" for UUID \"{subject_uuid}\"?\nType \"Y\" + \"ENTER\" to CONFIRM - Anything else + \"ENTER\" to CANCEL")
                if userinput.lower() != "y":
                    log(f"Terminal ABORTED the change of field \"{field}\" for UUID \"{subject_uuid}\".", level=1, perm=True)
                    return 6
                else:  
                    if not (field in ALLOWED_TERMINAL_FIELDS):
                        userinput = input("Are you SURE you're SURE? This is NOT an AUTHORIZED_TERMINAL_FIELD value.\nType \"Y\" + \"ENTER\" to CONFIRM - Anything else + \"ENTER\" to CANCEL")
                        if userinput.lower() != "y":
                            log(f"Terminal ABORTED the change of field \"{field}\" for UUID \"{subject_uuid}\" (backup safety check).", level=1, perm=True)
                            return 6
                        else:
                            # They're SURE...
                            log(f"Terminal is preparing to change field \"{field}\" for UUID \"{subject_uuid}\".", level=2, perm=True)
                    else:
                        pass # All OK!

        with Session(engine) as session: # ! The actual db changes
            statement = select(db_users).where(db_users.uuid == subject_uuid)
            result = session.exec(statement).first()
            if result:
                setattr(result, field, updvalue)
                session.commit() # Saves to file

                if terminal_override:
                    log(f"Terminal changed field \"{field}\" for UUID \"{subject_uuid}\".", level=1, perm=True)
                if admin_perms:
                    log(f"Admin UUID \"{initiating_jwt}\" changed field \"{field}\" for UUID \"{subject_uuid}\".", level=1, perm=True)
                else:
                    log(f"UUID \"{subject_uuid}\" changed field \"{field}\".", level=1, perm=True)
                return 0
            
            else: # User does NOT exist in db
                if admin_perms:
                    log(f"ABORTED - Admin UUID \"{initiating_jwt}\" tried changing field \"{field}\" for a nonexistant UUID (\"{subject_uuid}\")", level=2, perm=True)
                else:
                    log(f"ABORTED - Someone tried changing field \"{field}\" for a nonexistant UUID (\"{subject_uuid}\")", level=3, perm=True) # This should NEVER happen given the previous RegMode checks, so something went wrong in the code.
                return 1
    else: # Not a default allowed field
        log(f"ABORTED - Someone tried changing field \"{field}\" without Admin perms!", level=2, perm=True)
        return 2

def changeusersaveddata():
    with Session(engine) as session:
        pass


# ----------
# Query User
def getuserbyuuid(query_uuid):
    with Session(engine) as session:
        # 1. Build the statement
        statement = select(db_users).where(db_users.uuid == query_uuid) # Select() selects the table
        # 2. Run the statement and grab the result
        result = session.exec(statement).first() # Return ONE matching object or NONE
        # 3. Use the result
        if result:
            return result
        else:
            return None

def getuserbyusername(query_username):
    with Session(engine) as session:
        statement = select(db_users).where(db_users.username == query_username)
        result = session.exec(statement).first()
        if result:
            return result
        else:
            return None


# ----------
# Security Stuff
def addjwtid(jwtuuid): # This script is called by ? (TODO)
    with Session(engine) as session: # Checks for valid UUID
        statement = select(db_users).where(db_users.uuid == jwtuuid)
        result = session.exec(statement).first()
        if not result: # Inexistant UUID
            log(f"ABORTED - Attempted to create a JWT for a nonexistant UUID (\"{jwtuuid}\").", level=2, perm=True)
            return 1
        result_dict = result.model_dump()
        generated_jwt = sec.generateJWT(jwtuuid, result_dict["username"]) # Generates the JWT
        with Session(engine) as session: # Add the JWT Token and JTI to db
            new_jwt = db_jwts(
                # ID will be autopopulated by SQL
                uuid = str(jwtuuid),
                jti = str(generated_jwt["jti"])
            )
            # Stage to memory
            session.add(new_jwt)
            # Save to file
            session.commit()
            # Fetch auto-generated fields
            session.refresh(new_jwt)


def revokejwtid():
    with Session(engine) as session:
        pass

def checkjwt(jwt: str, uuid: str | None):
    """
    UUID v7 is (not counting hyphens):
    Pos 1-12: millisecond UNIX timestamp (strip hyphen)
    Pos 13: Version flag (7)
    Pos 14-16: Sub-millisecond (although it COULD be calculated, we won't use it.)
    Pos 17: Varient flag
    Pos 18-36: Random
    """

    jwt_verification = sec.verifyJWT(jwt)
    # Checks status field of main dict
    if jwt_verification["status"] == False:
        # Determine the issue
        if jwt_verification["details"] == "expired": # Seems like nothing malicious. Return code 2, signaling INVALID but don't become overly protective
            return 2
        elif jwt_verification["details"] == "invalid": # Likely malicious. Informs the code (if it doesn't check for != 0 and instead for individual error number) to become more protective, just in case.
            return 1
        else:
            return 1 # Just in case!

        # TODO: delete the below code in `with Session(engine) as session`, and change to check the function given UUID (if provided) and the JTI to see if it's in db (and compare against JWT UUID)
    
    """
    with Session(engine) as session:
        # 1. Check if the JWT exists in db
        statement = select(db_jwts).where(db_jwts.jwt == jwt)
        result = session.exec(statement).first()
        if not result: # Stop early: if JWT doesnt exist in db
            return {"status": "unlogged"} # TODO: appearently the dependencies require a dict with at least {status, sub} as keys
        result_dict = result.model_dump() # Turns the result into a valid python list

        # 2. Check if the JWT is still valid, via pos 1-12 of the JTI (uuid v7)
        jwt_timestamp_hex = (result_dict["jti"].replace("-", ""))[:12] # Since there is a hyphen, we first strip it (replace with nothing), and then get chars from index 0-12 - the stripping of the hyphen FIRST prevents unnessary complications during formatting
        jwt_timestamp_int = int(jwt_timestamp_hex, 16) # Converts secs from hex to b10
        unix_time_number = int(datetime.now(timezone.utc).timestamp()) # Get current UTC datetime and convert to seconds since 1970

        # 86400 seconds in a day
        if not ((unix_time_number + 86400) <= jwt_timestamp_int): # Stops early: if JWT is expired
            return {"status": "expired"}

        # 3. Final check - do the UUIDs and 
    """
        
        

def changeuserpassword(): # Although changeuseraccountinfo() could handle this, it is better to keep sensitive info seperate
    with Session(engine) as session:
        pass


# ----------
# Startup stuff

# 1. Find the absolute path to this script
script_dir = Path(__file__).resolve().parent
# 2. Go up one directory and points to the database file
database_file = script_dir.parent / "database.db"

# SQLite connection string
sqlite_url = f"sqlite:///{database_file}"

# Create the SQLModel engine
engine = create_engine(sqlite_url, echo=False)


def init_db():
	# Creates the DB file and all missing tables
	SQLModel.metadata.create_all(engine)

# Removed Database Creation Script for the default SQLModel db creation script
"""
# Database creation script (should only EVER run once!)
def createdatabase():
    try:
        with open(database_file, "x") as f: # Creates the file and instantly closes it. "X" allows for error logging.
            pass
        print("File created successfully!")
        return 1 # Database CREATED
    except FileExistsError: # Should NOT happen
        print("\033[1;33m[WARNING]\033[0m createdatabase() tried to create database.db, but faced FileExistsError. There may be something wrong with startup(), or database.db was added into root between the time of the check and attempted file creation.") # \033[1;33m sets it to bolded yellow, and \033[0m resets the colors
    except PermissionError:
        print("\033[1;31m[FATAL]\033[0m Does not have permission to create the file.") # \033[1;31m sets it to bolded red, and \033[0m resets the colors
        raise # Errors out

# Startup file check
def startup(ranfromapp):
    if database_file.is_file(): # Checks if the file exists
        return 0 # Database EXISTS
    else:
        if ranfromapp == True: # Since app.py calls on it, we can safely run createdatabase and return its results
            return createdatabase()
        else: # Createdatabase() called this script, and the file creation failed - quits the program to prevent recusive loops
            print("\033[1;31m[FATAL]\033[0m createdatabase() tried to create the database and suceeded, but the file was moved or deleted between the time of creation and checking.") # \033[1;31m sets it to bolded red, and \033[0m resets the colors
            raise FileNotFoundError
            return 2 # Unused status code (failure)         
"""